from api.main import CountryRisk

MOCK_COUNTRIES = [
    CountryRisk(country_code="SYR", country_name="Syria", conflict_probability_1y=0.91, regime_change_probability_1y=0.34, risk_score=0.88, risk_trend="stable", top_features=["Ongoing civil war", "Neighbor conflict spillover", "GDP collapse"], gdp_growth=-2.1, inflation=84.2, polity_score=-7),
    CountryRisk(country_code="SDN", country_name="Sudan", conflict_probability_1y=0.87, regime_change_probability_1y=0.61, risk_score=0.85, risk_trend="up", top_features=["Military factional conflict", "Regime instability", "Food insecurity"], gdp_growth=-12.3, inflation=63.8, polity_score=-6),
    CountryRisk(country_code="ETH", country_name="Ethiopia", conflict_probability_1y=0.74, regime_change_probability_1y=0.28, risk_score=0.71, risk_trend="down", top_features=["Ethnic conflict history", "Tigray region", "Economic stress"], gdp_growth=6.1, inflation=28.4, polity_score=1),
    CountryRisk(country_code="MMR", country_name="Myanmar", conflict_probability_1y=0.82, regime_change_probability_1y=0.47, risk_score=0.79, risk_trend="up", top_features=["Post-coup insurgency", "Military junta", "Sanctions pressure"], gdp_growth=-5.9, inflation=15.7, polity_score=-8),
    CountryRisk(country_code="AFG", country_name="Afghanistan", conflict_probability_1y=0.69, regime_change_probability_1y=0.19, risk_score=0.72, risk_trend="stable", top_features=["Taliban governance", "Economic collapse", "Humanitarian crisis"], gdp_growth=-20.7, inflation=9.1, polity_score=-10),
    CountryRisk(country_code="UKR", country_name="Ukraine", conflict_probability_1y=0.95, regime_change_probability_1y=0.08, risk_score=0.91, risk_trend="stable", top_features=["Active war with Russia", "Territorial control loss", "Infrastructure damage"], gdp_growth=-29.1, inflation=20.2, polity_score=6),
    CountryRisk(country_code="YEM", country_name="Yemen", conflict_probability_1y=0.78, regime_change_probability_1y=0.38, risk_score=0.80, risk_trend="stable", top_features=["Civil war ongoing", "Humanitarian crisis", "Proxy conflict"], gdp_growth=-1.0, inflation=22.3, polity_score=-2),
    CountryRisk(country_code="COD", country_name="DR Congo", conflict_probability_1y=0.76, regime_change_probability_1y=0.31, risk_score=0.74, risk_trend="up", top_features=["Eastern insurgency", "M23 rebel activity", "Resource conflict"], gdp_growth=6.2, inflation=41.5, polity_score=-1),
    CountryRisk(country_code="NGA", country_name="Nigeria", conflict_probability_1y=0.58, regime_change_probability_1y=0.22, risk_score=0.55, risk_trend="stable", top_features=["Boko Haram activity", "Bandit attacks", "Oil revenue dependence"], gdp_growth=2.9, inflation=28.9, polity_score=4),
    CountryRisk(country_code="MLI", country_name="Mali", conflict_probability_1y=0.72, regime_change_probability_1y=0.45, risk_score=0.69, risk_trend="up", top_features=["Jihadist insurgency", "Military junta", "Sahel instability"], gdp_growth=2.4, inflation=3.9, polity_score=-5),
    CountryRisk(country_code="RUS", country_name="Russia", conflict_probability_1y=0.88, regime_change_probability_1y=0.12, risk_score=0.72, risk_trend="stable", top_features=["Active war in Ukraine", "Sanctions exposure", "Autocratic stability"], gdp_growth=3.6, inflation=7.4, polity_score=-5),
    CountryRisk(country_code="IRN", country_name="Iran", conflict_probability_1y=0.31, regime_change_probability_1y=0.24, risk_score=0.45, risk_trend="up", top_features=["Protest movements", "Nuclear tension", "Economic sanctions"], gdp_growth=4.7, inflation=45.8, polity_score=-7),
    CountryRisk(country_code="VEN", country_name="Venezuela", conflict_probability_1y=0.22, regime_change_probability_1y=0.31, risk_score=0.38, risk_trend="down", top_features=["Regime consolidation", "Oil revenue recovery", "Opposition weakness"], gdp_growth=5.0, inflation=189.8, polity_score=-7),
    CountryRisk(country_code="PRK", country_name="North Korea", conflict_probability_1y=0.18, regime_change_probability_1y=0.04, risk_score=0.42, risk_trend="stable", top_features=["Nuclear program escalation", "Extreme autocracy", "Isolation"], gdp_growth=-1.8, inflation=0.0, polity_score=-10),
    CountryRisk(country_code="PAK", country_name="Pakistan", conflict_probability_1y=0.44, regime_change_probability_1y=0.37, risk_score=0.48, risk_trend="up", top_features=["Political crisis", "IMF dependency", "TTP resurgence"], gdp_growth=2.4, inflation=23.4, polity_score=4),
    CountryRisk(country_code="USA", country_name="United States", conflict_probability_1y=0.03, regime_change_probability_1y=0.02, risk_score=0.06, risk_trend="stable", top_features=["Democratic stability", "Strong institutions", "Military capability"], gdp_growth=2.8, inflation=3.2, polity_score=10),
    CountryRisk(country_code="DEU", country_name="Germany", conflict_probability_1y=0.02, regime_change_probability_1y=0.01, risk_score=0.04, risk_trend="stable", top_features=["EU membership", "NATO security", "Democratic institutions"], gdp_growth=-0.3, inflation=5.9, polity_score=10),
    CountryRisk(country_code="CHN", country_name="China", conflict_probability_1y=0.12, regime_change_probability_1y=0.05, risk_score=0.22, risk_trend="stable", top_features=["Taiwan tension", "Authoritarian stability", "Economic slowdown"], gdp_growth=5.2, inflation=0.2, polity_score=-7),
    CountryRisk(country_code="BRA", country_name="Brazil", conflict_probability_1y=0.05, regime_change_probability_1y=0.06, risk_score=0.10, risk_trend="down", top_features=["Democratic recovery", "Lula governance", "Deforestation tension"], gdp_growth=2.9, inflation=4.6, polity_score=8),
    CountryRisk(country_code="ISR", country_name="Israel", conflict_probability_1y=0.81, regime_change_probability_1y=0.14, risk_score=0.77, risk_trend="up", top_features=["Gaza conflict", "Regional escalation", "Iran proxy threat"], gdp_growth=1.8, inflation=3.1, polity_score=9),
]
